version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sprinkles-pinchflat_server_1
      APP_PORT: 8945
    container_name: pinchflat_app_proxy_1
  server:
        image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=America/New York
    ports:
      - '8945:8945'
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${UMBREL_HOME}/Downloads:/downloads
    environment:
      
    container_name: sprinkles-pinchflat_server_1
    restart: on-failure
    user: "1000:1000"
    init: true
